### ISSUE TITLE
Question: about alternatives  you considered

### ISSUE THREAD

**Issue by ccoVeille** [s0ders/go-semver-release#43]

**Comment by s0ders** [comment]
I was not aware of this project. It states that it's a Go version of the [semantic-release](https://github.com/semantic-release/semantic-release) project written in JS.
This project (go-semver-release) tries to focus on versionning only (no package publishing, change log generation etc.) with as little dependencies as possible for security and perf. reasons.

While these projects offer more features, I believe they also bring a small overhead when people sometimes simply want a semantic version number and a Git tag to start versionning their projects, which is why I started building this project.

**Comment by ccoVeille** [comment]
I think you should copy paste this in your README

I often find interesting when I read such things in the readme.

It gives context and reply question such like mine: how is this project from the others I know

**Comment by s0ders** [comment]
I agree, will do as soon as possible !

**Comment by ccoVeille** [comment]
You could also explain how you project is not related to https://github.com/coreos/go-semver and how it differs

People might be confused with project name proximity.
